---
title: "TBD"
author: "Rachael Lam"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  bookdown::pdf_document2:
subtitle: "TBD"
abstract: "TBD"
thanks: 'Code and data are available at: https://github.com/rachaellam/edu-suspension-analysis.git.'
toc: yes
bibliography: references.bib
---

```{r setup, include=FALSE}

library(here)
library(devtools)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(scales)

```

# Introduction



Criminalizing youth

initial findings:
there is some relationship between number of days missed due to suspensions and salary expenditures of all school personnel
there is some relationship between in school suspensions and number and salary expenditures of all school personnel
there is some relationship between number of days missed due to suspensions and salary of teachers but no relationship between days missed and salary of other personnel (aid, support services, administration)
there is some relationship between number of in school suspensions and number of teachers. this is probably due to more teachers = more students = more suspensions
there is no relationship between number of in school suspensions and number of teachers per student... odd
looking at the 10 most populous states, half of them have a relationship between days missed and salary of all school personnel but the other half have no relationship. Broadening to the entire population, there is a strong relationship so there is something to explore there.

# Data

High school data includes schools who offer only grades 9-12. No schools are included that only offer partial grades (ex. 10-12)

Excluded:
Only using high school data (maybe include other analysis depending on length)
Raw data had over 1800 columns, so I removed all columns that were not necessary to this analysis including what types of classes are offered (algebra, geography, science, etc.).
Grouped all students, regardless of race, to sum all suspensions. This has some ethical issues. This could also change the analysis if race was included.
Disabilities

Part of the analysis:
1. Number of days missed due to suspension (TOT_DAYSMISSED) - Created this variable by summing total days missed for females (TOT_DAYSMISSED_F) and total days missed for males (OT_DAYSMISSED_M). I chose this because it speaks to the severity of the suspension. More days missed means the suspensions were for a longer period of time.
2. Salary expenditures for total personnel without federal funding (COST_PER_STUDENT_WOFED) - Created this variable by dividing the salary with the number of students to understand how much each school was spending per student. 
3. Amount of non-personnel expenditures associated with activities (COST_PER_STUDENT_NPE_WOFED) - cost per student creation.
Might include variables that separate total personnel such as teachers, administration, support services, instructional aid)
4. all expenditures are WOFED (without federal funding) to focus on state expenditures rather than federal intervention

DC and Hawaii are not included because there are no schools that only offer 9-12. Schools either offer more grades, fewer grades or ungraded.
Focus on schools that report their data, excluding ones that do not which could prove problematic. What are they type of schools that are not reporting stats?
Self reporting raises the question of accurate reporting

# Model

Will be using multiple linear regression. Cannot use a diff in diff approach because there are not enough variables. Although school districts are available, they do not match records that I can find.

# Results

The question here is if an increase in spend per student is associated with a decrease in in schools suspensions or the severity of school suspensions (number of days missed). Although the model suggests that there is some relationship, it is not a representation of a causal relationship. There are many factors that could lead to high suspension rates in schools. Studies have been done that determine high-suspending schools are usually schools from in low-income communities and have a higher population of minority students. 

Funding of schools relies on the majority of state and local funding. Local funding is collected from property taxes and other taxes such as sales and income. This automatically leads to a discrepancy as low-income communities collect less property tax (cheaper housing) and less sales and income tax (less income = less spending). Very few states attempt to equalize school funding, and even in states that do, there is still a large discrepancy with the amount of resources schools receive.

# Discussion

speak to causality, what you would do, and why you can't do it
Not able to do diff in diff so there could be some factors causing suspensions rates that are not discussed in the paper. States could vary drastically, especially in political values, thus outlooks on criminality, punishment and tolerance.

# Conclusion

# Lit review discussion points
Rebecca Hinze-Pifera and Lauren Sartain: https://doi.org/10.1080/0161956X.2018.1435051
- difficult to identify causal impact because of the many factors that go into deciding student suspension including personal biases
- data quality problems due to schools under reporting
- suspensions cause increase fear of crime, teacher attrition, anger, disconnect from school, impacts of missing school
- negative impacts for not only students who are suspended but students who attend schools with high suspension rates
- suspension inequality (race, gender, LGBTQ, special needs, socioeconomic factors)

Jason Jabbari, Odis Johnson Jr: https://doi-org.myaccess.library.utoronto.ca/10.1177%2F0042085920902256
- zero tolerance policies 1990s
- exclusionary practices
- urban communities with heightened police surveillance
- school to prison pipeline
- study that found students who attend high-suspension schools are negatively affected, even if they do not themselves receive a suspension.
- mention a study that found students who received ISS suffered a lower GPA and higher dropout rates even though ISS has been seen as a less punitive form of punishment.

Talisha Lee, Dewey Cornell, Anne Gregory, and Xitao Fan: doi:10.1353/etc.2011.0014
- references studies that have been done that discuss the characteristics of a school with drop out rates
- schools wit a higher percentage of low income students have higher drop out rates
- higher rate of students from low socioeconomic backgrounds and a greater percentage of minority students were associated with high rates of school suspensions
- schools with majority white students had more financial resources than schools with high percentage of minority students
- drop out rates for rural areas tend to be lower than urban areas
- reliant on schools to report drop out rates/retention rates but doesn't account for student mobility/declining school populations

E. Christine Baker-Smith: https://doi.org/10.1080/0161956X.2018.1435043
- exclusionary discipline related to lower levels of educational attainment, involvement in the criminal justice system, poor labour market outcomes
- gun free schools act (1994) required any state "receiving federal funds to have a state law in effect requiring local educational agencies to expel, for at least one year, any student who is determined to have brought a weapon to school"
- this act allowed schools to adopt harsher exclusionary practices against violent offenses, but it also brough an increased use of out of school suspensions for non-violent offences such as vulgar language, dress code violations, tardiness, or generic insubordination. 
- zero tolerance policies
- a randomized experiment found that teachers were more likely to punish a student who committed a second offense if they were black







